name: Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch: {}


jobs:
  check:
    name: Check Python
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install
        run: poetry install

    #   - name: Type check with pyright
    #     run: poetry run pyright ssip

      - name: Check formatting with ruff
        uses: chartboost/ruff-action@v1
        with:
          src: "./ssip"
          args: format --check
          version: 0.4.0

      - name: Lint with ruff
        uses: chartboost/ruff-action@v1
        with:
          src: "./ssip"
          args: check

      - name: Run tests
        run: poetry run pytest
